spring:
    datasource:
        url: jdbc:postgresql://postgres:5432/monolith_authdb   # 👈 host é "postgres", NÃO "localhost"
        username: auth
        password: authpwd
    jpa:
        hibernate:
            ddl-auto: validate
    flyway:
        enabled: true
