spring:
    datasource:
        url: jdbc:postgresql://postgres:5432/monolith_authdb
        username: auth
        password: authpwd
    jpa:
        hibernate:
            ddl-auto: validate
    flyway:
        enabled: true
        user: auth        # Forçar o Flyway a usar o usuário 'auth'
        password: authpwd
        url: jdbc:postgresql://postgres:5432/monolith_authdb
