spring:
    jpa:
        hibernate:
            ddl-auto: update
    flyway:
        enabled: false

# Configurações do JWT
security:
    access-jwt:
        secret: "chaveParaDesenvolvimentoTrocarQuandoEntrarEmProducao" # Trocar na produção
        expiration: 900000  # 15 minutos em milissegundos
    refresh-token:
        expiration: 2592000000 # 30 dias em milissegundos

