spring:
    flyway:
        baseline-on-migrate: true    # se o DB jรก tem tabelas manuais
        locations: classpath:db/migration
    config:
        activate:
            on-profile: dev
    datasource:
        url: jdbc:postgresql://localhost:5432/monolith_authdb
        username: auth
        password: authpwd
    jpa:
        hibernate:
            ddl-auto: update   # convenient for dev (Flyway later)
logging:
    level:
        root: info
