spring:
    config:
        activate:
            on-profile: dev
    datasource:
        url: jdbc:postgresql://db:5432/monolith_authdb
        username: auth
        password: authpwd
    jpa:
        hibernate:
            ddl-auto: update   # convenient for dev (Flyway later)
logging:
    level:
        root: info
