spring:
    jpa:
        hibernate:
            ddl-auto: update
    flyway:
        enabled: false

# Configurações do JWT
security:
    frontend-url: "http://localhost:5173"
    access-jwt:
        secret: "chaveParaDesenvolvimentoTrocarQuandoEntrarEmProducao" # Trocar na produção
        expiration: 900000  # 15 minutos em milissegundos
    refresh-token:
        expiration: 2592000000 # 30 dias em milissegundos

#Configuração dos logs
logging:
  level:
    org.springframework.security: DEBUG
    com.victorsaraiva: DEBUG        # (opcional) seus pacotes

