spring:
    datasource:
        url: jdbc:postgresql://postgres:5432/monolith_authdb   # 👈 host é "postgres", NÃO "localhost"
        username: auth
        password: authpwd
    jpa:
        hibernate:
            ddl-auto: validate
    flyway:
        enabled: true
security:
    access-jwt:
        secret: "chaveParaPropositoDeTestesApenasNaoUsarEmProducao" # Trocar na produção
        expiration: 900000  # 15 minutos em milissegundos

# Configurações da API
api:
    base-url: "/api/v1"
