spring:
    datasource:
        url: jdbc:postgresql://postgres:5432/monolith_authdb
        username: auth
        password: authpwd
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: validate
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
    flyway:
        enabled: true
        user: auth
        password: authpwd
        url: jdbc:postgresql://postgres:5432/monolith_authdb
        baseline-on-migrate: true
        locations: classpath:db/migration
