spring:
    datasource:
        url: jdbc:postgresql://postgres:5432/monolith_authdb   # host é "postgres", NÃO "localhost"
        username: auth
        password: authpwd
    jpa:
        hibernate:
            ddl-auto: validate
    flyway:
        enabled: true
security:
    frontend-url: "http://localhost:5173"
    access-jwt:
        secret: "chaveParaPropositoDeTestesApenasNaoUsarEmProducao" # Trocar na produção
        expiration: 900000  # 15 minutos em milissegundos

    refresh-token:
        expiration: 2592000000 # 30 dias em milissegundos

