name: CI

on:
    push:
        branches: [ main ]
    pull_request:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            # 1) Checkout do c칩digo
            - name: Checkout
              uses: actions/checkout@v4

            # 2) Garante que o daemon Docker est치 ativo
            - name: Ensure Docker daemon is running
              run: |
                  sudo systemctl start docker
                  docker info

            # 3) Maven wrapper execut치vel
            - name: Make wrapper executable
              run: chmod +x mvnw

            # 4) Java 21 (Temurin)
            - name: Set up JDK 21
              uses: actions/setup-java@v4
              with:
                  java-version: 21
                  distribution: temurin
                  cache: maven

            # 5) Build + testes com profile test (Flyway + Testcontainers)
            - name: Build & Test
              run: ./mvnw --batch-mode verify

            # 6) Publica relat칩rios de teste mesmo se falhar
            - name: Upload Surefire reports
              if: always()
              uses: actions/upload-artifact@v4
              with:
                  name: surefire-reports
                  path: target/surefire-reports
