name: CI

on:
    push:
        branches: [ main ]
    pull_request:

jobs:
    build:
        runs-on: ubuntu-latest

        services:
            postgres:
                image: postgres:17.4
                env:
                    POSTGRES_DB: monolith_authdb
                    POSTGRES_USER: auth
                    POSTGRES_PASSWORD: authpwd
                    POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
                ports:
                    - 5432:5432
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5

        steps:
            # 0) Adicionar depois da verificação de saúde do PostgreSQL
            -   name: Create root user
                run: |
                    docker exec -i $(docker ps -q -f 'name=postgres') psql -U auth -d monolith_authdb -c "CREATE USER root WITH PASSWORD 'password' SUPERUSER;"

            # 1) Checkout do código
            -   name: Checkout
                uses: actions/checkout@v4

            # 2) Garante que o daemon Docker está ativo
            -   name: Ensure Docker daemon is running
                run: |
                    sudo systemctl start docker
                    docker info

            # 3) Maven wrapper executável
            -   name: Make wrapper executable
                run: chmod +x mvnw

            # 4) Java 21 (Temurin)
            -   name: Set up JDK 21
                uses: actions/setup-java@v4
                with:
                    java-version: 21
                    distribution: temurin
                    cache: maven

            # 5) Build + testes com profile test (Flyway + Testcontainers)
            -   name: Build & Test
                run: SPRING_PROFILES_ACTIVE=test ./mvnw --batch-mode verify
                env:
                    SPRING_DATASOURCE_USERNAME: auth
                    SPRING_DATASOURCE_PASSWORD: authpwd
                    SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/monolith_authdb

            # 6) Publica relatórios de teste mesmo se falhar
            -   name: Upload Surefire reports
                if: always()
                uses: actions/upload-artifact@v4
                with:
                    name: surefire-reports
                    path: target/surefire-reports
        # Resto dos steps continua igual...

