name: CI

on:
    push:
        branches: [ main ]
    pull_request:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   name: Make wrapper executable
                run: chmod +x mvnw

            -   name: Set up JDK 21
                uses: actions/setup-java@v4
                with:
                    java-version: 21
                    distribution: temurin
                    cache: maven

            -   name: Build & test (profile=test)
                run: SPRING_PROFILES_ACTIVE=test ./mvnw --batch-mode verify

            -   name: Upload Surefire reports
                if: always()
                uses: actions/upload-artifact@v4
                with:
                    name: surefire-reports
                    path: target/surefire-reports
