name: CI

on:
    push:
        branches: [ main ]
    pull_request:

jobs:
    build:
        runs-on: ubuntu-latest

        permissions:
            contents: read
            security-events: write    # para alertas do dependabot

        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Set up JDK 21
              uses: actions/setup-java@v4
              with:
                  java-version: 21
                  distribution: temurin
                  cache: maven

            - name: Build & test
              run: ./mvnw --batch-mode verify

            - name: Upload test report
              if: always()
              uses: actions/upload-artifact@v4
              with:
                  name: surefire-reports
                  path: target/surefire-reports
