name: CI

on:
    push:
        branches: [ main ]
    pull_request:

jobs:
    build:
        runs-on: ubuntu-latest

        permissions:
            contents: read
            security-events: write    # para alertas do dependabot

        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
            - run: chmod +x mvnw

            - name: Set up JDK 21
              uses: actions/setup-java@v4
              with:
                  java-version: 21
                  distribution: temurin
                  cache: maven

            - name: Build & test
              run: SPRING_PROFILES_ACTIVE=dev ./mvnw --batch-mode verify

            - name: Upload test report
              if: always()
              uses: actions/upload-artifact@v4
              with:
                  name: surefire-reports
                  path: target/surefire-reports

        services:
            postgres:
                image: postgres:17.4
                env:
                    POSTGRES_DB: monolith_authdb
                    POSTGRES_USER: auth
                    POSTGRES_PASSWORD: authpwd
                ports:
                    - 5432:5432
                options: >-
                    --health-cmd="pg_isready -U auth -d monolith_authdb" --health-interval=10s
                    --health-timeout=5s --health-retries=5                          
